# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 673)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(105, 20, 21, 16))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(135, 20, 71, 20))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(215, 20, 41, 16))
        self.label_2.setObjectName("label_2")
        self.old = QtWidgets.QLineEdit(self.centralwidget)
        self.old.setGeometry(QtCore.QRect(255, 20, 71, 20))
        self.old.setObjectName("old")
        self.grnder = QtWidgets.QLineEdit(self.centralwidget)
        self.grnder.setGeometry(QtCore.QRect(375, 20, 71, 20))
        self.grnder.setObjectName("grnder")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(345, 20, 31, 16))
        self.label_4.setObjectName("label_4")
        self.dele = QtWidgets.QPushButton(self.centralwidget)
        self.dele.setGeometry(QtCore.QRect(675, 20, 101, 23))
        self.dele.setObjectName("dele")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(31, 20, 16, 16))
        self.label_5.setObjectName("label_5")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(40, 20, 61, 20))
        self.id.setObjectName("id")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 801, 581))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 24, 47, 13))
        self.label_6.setObjectName("label_6")
        self.com = QtWidgets.QComboBox(self.centralwidget)
        self.com.setGeometry(QtCore.QRect(510, 20, 81, 22))
        self.com.setObjectName("com")
        self.con = QtWidgets.QPushButton(self.centralwidget)
        self.con.setGeometry(QtCore.QRect(600, 20, 61, 23))
        self.con.setObjectName("con")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Панель умного коровника"))
        self.label.setText(_translate("MainWindow", "Имя"))
        self.label_2.setText(_translate("MainWindow", "Возраст"))
        self.label_4.setText(_translate("MainWindow", "Пол"))
        self.dele.setText(_translate("MainWindow", "Удалить"))
        self.label_5.setText(_translate("MainWindow", "id"))
        self.label_6.setText(_translate("MainWindow", "Com Port"))
        self.con.setText(_translate("MainWindow", "connect"))
