# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 70, 1011, 761))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 30, 81, 16))
        self.label.setObjectName("label")
        self.rfid = QtWidgets.QLineEdit(self.centralwidget)
        self.rfid.setGeometry(QtCore.QRect(130, 30, 113, 20))
        self.rfid.setObjectName("rfid")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(490, 30, 75, 23))
        self.ok.setObjectName("ok")
        self.rec = QtWidgets.QLineEdit(self.centralwidget)
        self.rec.setGeometry(QtCore.QRect(340, 30, 113, 20))
        self.rec.setObjectName("rec")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1090, 50, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.question = QtWidgets.QLineEdit(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(1020, 740, 241, 41))
        self.question.setObjectName("question")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(1020, 790, 241, 41))
        self.send.setObjectName("send")
        self.answer = QtWidgets.QTextEdit(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(1020, 90, 251, 641))
        self.answer.setObjectName("answer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RFID коровы"))
        self.label_2.setText(_translate("MainWindow", "Рекомендация"))
        self.ok.setText(_translate("MainWindow", "Применить"))
        self.label_3.setText(_translate("MainWindow", "Ассистент"))
        self.question.setPlaceholderText(_translate("MainWindow", "Введите вопрос"))
        self.send.setText(_translate("MainWindow", "Отправить"))
